In [1]:
import sys
sys.path.append('../src/')
from train import *

C:\Users\qypal\anaconda3\envs\pytorch_GPU\lib\_collections_abc.py:832: MatplotlibDeprecationWarning: Support for setting the 'text.latex.preamble' or 'pgf.preamble' rcParam to a list of strings is deprecated since 3.3 and will be removed two minor releases later; set it to a single string instead.
  self[key] = other[key]


## Test dataset.py

In [12]:
dataset="lilac"
current, voltage, labels = get_data(submetered=False, data_type=dataset, isc=False)
labels = get_correct_labels_lilac(labels)

#perform label enconding
le = LabelEncoder()
le.fit(labels)
y = le.transform(labels)

skf = StratifiedKFold(n_splits=4,random_state=42,shuffle=True)
train_index, test_index = next(skf.split(current, y))

input_feature = generate_input_feature(current, voltage, image_type="adaptive", width=30, multi_dimension=True)
Xtrain, Xtest = input_feature[train_index], input_feature[test_index]
ytrain, ytest = y[train_index], y[test_index]

tra_loader, val_loader=get_loaders(Xtrain, Xtest, ytrain, ytest, batch_size=16)
print("Load LILAC data successfully.")

0it [00:00, ?it/s]

Load lilac aggregated data from ../data/lilac/aggregated/


processed: 1324: : 1324it [08:17,  2.66it/s]

Load LILAC data successfully.


## Test Train.py

In [2]:
# get_user_inputs()
dataset, image_type, eps, delta, width = get_user_inputs()

Input l for lilac, p for plaid)l
Input a for AWRG, v for VI-graptha
Input epsilon (suggest 10):10
Input delta (suggest 10):10
Input width (suggest 50):50


In [3]:
# create_trainer()
dataset = 'lilac'
image_type = 'adaptive'
eps = 10
delta = 10
width = 50
batch_size = 16
num_class, trainer = create_trainer(dataset=dataset, image_type=image_type, multi_dimension=True, batch_size=batch_size, 
                                    width=width, eps=eps, delta=delta)

processed: 10: : 9it [00:00, 69.41it/s]

Load lilac aggregated data from ../data/lilac/aggregated/
correct labels for some appliances


processed: 1324: : 1324it [00:19, 67.75it/s]


Trainer for lilac created.


In [4]:
# train_the_model()
epochs = 10
checkpoint = train_the_model(trainer, dataset, image_type, epochs, width, multi_dimension=True)

Epoch 9: 100%|██████████| 63/63 [00:02<00:00, 27.27it/s, loss=0.399, score=0.865]


In [2]:
file_name = 'plaid_adaptive_50'
plot_learning_curve(file_name)

[[0.00000000e+00 1.80551717e+00 1.80434932e+00 2.69642857e-01
  2.65625000e-01]
 [1.00000000e+00 1.04019796e+00 1.03708189e+00 5.97321429e-01
  6.09375000e-01]
 [2.00000000e+00 7.06152710e-01 7.40534660e-01 8.25892857e-01
  8.12500000e-01]
 [3.00000000e+00 6.32097077e-01 6.62460482e-01 8.00892857e-01
  8.09895833e-01]
 [4.00000000e+00 5.64222881e-01 6.07967814e-01 7.98214286e-01
  7.96875000e-01]
 [5.00000000e+00 4.65729771e-01 5.00666446e-01 8.16071429e-01
  8.15104167e-01]
 [6.00000000e+00 3.89051745e-01 4.33712023e-01 9.23214286e-01
  9.08854167e-01]
 [7.00000000e+00 3.93946573e-01 4.38562492e-01 8.91964286e-01
  8.85416667e-01]
 [8.00000000e+00 3.40009541e-01 4.00410728e-01 9.06250000e-01
  8.85416667e-01]
 [9.00000000e+00 3.55476793e-01 4.10996379e-01 8.43750000e-01
  8.35937500e-01]
 [1.00000000e+01 2.73819751e-01 3.05527482e-01 9.25892857e-01
  9.19270833e-01]
 [1.10000000e+01 2.29388447e-01 2.82694732e-01 9.57142857e-01
  9.29687500e-01]
 [1.20000000e+01 1.97179790e-01 2.689489

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 7200x4800 with 1 Axes>

In [5]:
# test_the_model()
test_the_model(trainer, num_class, checkpoint)

In [3]:
import numpy as np
a=np.arange(9).reshape(3,3)
print(a)
print(a[1:,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 6]
